import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={` ${inter.className}`}lang="en">
      <body className={`siteContainer fullCover `}>
        {children}
        </body>
    </html>
  );
}
